services:
  - type: web
    name: conflict-analysis-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: conflict-db
          property: connectionString
    autoDeploy: false

databases:
  - name: conflict-db
    databaseName: conflictdb
    user: conflictuser
    plan: free